# Generated by Django 4.2.3 on 2023-07-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='appartment_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_details',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='exit', max_length=500),
            preserve_default=False,
        ),
    ]
