# Generated by Django 4.2.3 on 2023-07-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_appartment_name_listing_contact_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_details',
            field=models.IntegerField(verbose_name=12),
        ),
    ]
