# Generated by Django 4.2.3 on 2023-07-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='t_details',
        ),
    ]
