# Generated by Django 4.2.3 on 2023-07-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_details',
            field=models.IntegerField(default=0),
        ),
    ]
